language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  app: itch-roulette
  api_key:
    secure: cgPK3KH7WIFZCWutcCAAnf+v8YReVIXXSETQwc64WzG9ErL2CKj5ROFWM54vEqdOQgI/2vbinCgbkvgh9Hs0TLHxFt+A6djrQnXeY7atr3XtwQ9zfP/Qhadfcuu20sKJLYTJYZBysDS7pCTE2pdvTXU+om+UIGmekmhQwEL7fvE=
  on:
    python: 2.7
